/* SPDX-License-Identifier: AGPL-3.0-or-later
   Copyright (C) 2026 PUDDY Inc. <legal@puddystudios.com>
   SUNMAP service worker - generated by scripts/render.py, do not hand-edit. */
'use strict';
var VERSION = 'babc023095';
var CACHE = 'sunmap-' + VERSION;
var EXT = 'sunmap-ext';
var CORE = [
  '/',
  '/index.html',
  '/manifest.json',
  '/sunmap-worker.js',
  '/sunmap-geo.js',
  '/favicon.svg'
];
/* Everything the on-device engine needs to run with no network, plus the root
   chrome, the OG card and the icons. Cached TOLERANTLY: any one of these
   missing must not fail the install, because the OG card comes from
   scripts/generate-og.mjs and the icons from scripts/make-icons.sh, and either
   may not have been run yet. Once they are cached, SUNMAP solves any day
   fully offline. */
var EXTRAS = [
  '/puddy-tools.js?v=15', '/puddy-logo.svg', '/og/sunmap-og.png',
  '/vendor/sweph/swisseph.js', '/vendor/sweph/swisseph.wasm',
  '/data/ephe/seas_18.se1', '/data/ephe/semo_18.se1', '/data/ephe/sepl_18.se1',
  '/icons/icon-192.png', '/icons/icon-512.png',
  '/icons/icon-maskable-512.png', '/icons/icon-180.png',
  '/icons/icon-32.png', '/icons/icon-16.png', '/favicon.ico'
];

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(CACHE).then(function (c) {
      /* cache:'reload' bypasses the browser HTTP cache so installs always
         snapshot fresh-from-edge, never a stale disk-cached copy. */
      return c.addAll(CORE.map(function (u) { return new Request(u, { cache: 'reload' }); })).then(function () {
        return Promise.allSettled(EXTRAS.map(function (u) { return c.add(new Request(u, { cache: 'reload' })); }));
      });
    }).then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.filter(function (k) {
        return k.indexOf('sunmap-') === 0 && k !== CACHE && k !== EXT;
      }).map(function (k) { return caches.delete(k); }));
    }).then(function () { return self.clients.claim(); })
  );
});

function swr(req, cacheName) {
  return caches.open(cacheName).then(function (c) {
    return c.match(req).then(function (hit) {
      /* no-cache = revalidate against the edge (conditional GET), so the
         background refresh can never re-absorb a stale browser-cache copy. */
      var refresh = fetch(req, { cache: 'no-cache' }).then(function (res) {
        if (res && res.ok) c.put(req, res.clone());
        return res;
      }).catch(function () { return hit; });
      return hit || refresh;
    });
  });
}

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  var url = new URL(req.url);

  /* Page navigations: network-first so new builds land immediately; cached page offline. */
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req, { cache: 'no-cache' }).then(function (res) {
        if (res && res.ok) {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return res;
      }).catch(function () {
        return caches.match(req).then(function (hit) {
          return hit || caches.match('/').then(function (hub) {
            return hub || caches.match('/index.html');
          });
        });
      })
    );
    return;
  }

  /* Same-origin assets (the engine, the ephemerides, icons, OG, chrome): stale-while-revalidate. */
  if (url.origin === self.location.origin) {
    e.respondWith(swr(req, CACHE));
    return;
  }

  /* Webfonts (Google Fonts / Fontshare): cache so the installed app keeps its type offline. */
  if (/fonts\.googleapis\.com|fonts\.gstatic\.com|api\.fontshare\.com|cdn\.fontshare\.com/.test(url.host)) {
    e.respondWith(swr(req, EXT));
  }
});
