#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 PUDDY Inc.
#
# SUNMAP icon set - every raster icon the page and the manifest reference, rasterized
# from favicon.svg and from nothing else. favicon.svg is itself generated by
# scripts/render.py out of the same _GEOM the on-page crest uses, so the emblem cannot
# drift between the tab, the home screen and the page. No colour is chosen here: the
# only colours that can reach these files are the ones already in the SVG, PLUTO
# sand-300 #ceba9d and #fff, on the black ground the manifest declares.
#
# Run AFTER scripts/render.py. Needs rsvg-convert and ImageMagick, which is why this is
# a separate step - render.py stays pure python3 with no binary toolchain.
#
#   sh scripts/make-icons.sh
set -eu

cd "$(dirname "$0")/.."
SRC=favicon.svg
BG='#000000'
[ -f "$SRC" ] || { echo "no $SRC - run scripts/render.py first" >&2; exit 1; }
mkdir -p icons

# Square icons, crest edge to edge on black.
for s in 16 32 180 192 512; do
  rsvg-convert -w "$s" -h "$s" -b "$BG" "$SRC" -o "icons/icon-$s.png"
done

# Maskable: Android may crop to any shape inside the icon, so the crest has to sit in
# the safe zone - the centre circle of 80% diameter. Render it at 72% and pad to 512.
rsvg-convert -w 369 -h 369 -b "$BG" "$SRC" -o icons/_m.png
magick icons/_m.png -background "$BG" -gravity center -extent 512x512 icons/icon-maskable-512.png
rm -f icons/_m.png

# favicon.ico - the unconditional /favicon.ico fetch that browsers and social scrapers
# make whether or not the page links one. Multi-size, same crest.
magick icons/icon-16.png icons/icon-32.png -colors 256 favicon.ico

echo "wrote icons/ (16 32 180 192 512 + maskable-512) + favicon.ico from $SRC"
